
typedef struct Thing_s* Thing;
typedef struct Prop_s* Prop;
#define number double

extern const void* null;

Thing get_link(float i);
float sensor(Thing target, Prop property);

void control_enabled(Thing target, float value);
void control_shoot(Thing target, float x, float y, float shoot);
void control_color(Thing target, float r, float g, float b);

float read(Thing target, float position);
void write(Thing target, float position, float value);

void draw_clear(float r, float g, float b);
void draw_color(float r, float g, float b, float a);
void draw_stroke(float v);
void draw_rect(float x, float y, float w, float h);
void draw_line_rect(float x, float y, float w, float h);
void draw_poly(float x, float y, float sides, float radius, float rotation);
void draw_line_poly(float x, float y, float sides, float radius, float rotation);
void draw_triangle(float x1, float y1, float x2, float y2, float x3, float y3);
void draw_image(float x, float y, Thing image, float size, float rotation);
void draw_flush(Thing target);

void print(float message);
void print_flush(Thing target);

Thing radar_player(Thing from, float order);

float min(float x, float y);
float max(float x, float y);
float sin(float x);
float cos(float x);
float tan(float x);
float asin(float x);
float acos(float x);
float atan(float x);
float atan2(float x, float y);
float length(float x, float y);
float log(float x);
float log10(float x);
float simplex2d(float x, float y);

extern const float C_TIME;
extern const float C_TICK;
extern const Thing C_THIS;
extern float C_COUNTER; // it's not const, but that doesnt mean you should change it

extern const Prop P_TOTALITEMS;
extern const Prop P_FIRSTITEM;
extern const Prop P_TOTALLIQUIDS;
extern const Prop P_TOTALPOWER;
extern const Prop P_ITEMCAPACITY;
extern const Prop P_LIQUIDCAPACITY;
extern const Prop P_POWERCAPACITY;
extern const Prop P_POWERNETSTORED;
extern const Prop P_POWERNETCAPACITY;
extern const Prop P_POWERNETIN;
extern const Prop P_POWERNETOUT;
extern const Prop P_AMMO;
extern const Prop P_AMMOCAPACITY;
extern const Prop P_HEALTH;
extern const Prop P_MAXHEALTH;
extern const Prop P_HEAT;
extern const Prop P_EFFICIENCY;
extern const Prop P_PROGRESS;
extern const Prop P_TIMESCALE;
extern const Prop P_ROTATION;
extern const Prop P_X;
extern const Prop P_Y;
extern const Prop P_SHOOT_X;
extern const Prop P_SHOOT_Y;
extern const Prop P_SIZE;
extern const Prop P_DEAD;
extern const Prop P_RANGE;
extern const Prop P_SHOOTING;
extern const Prop P_BOOSTING;
extern const Prop P_MINE_X;
extern const Prop P_MINE_Y;
extern const Prop P_MINING;
extern const Prop P_TEAM;
extern const Prop P_TYPE;
extern const Prop P_FLAG;
extern const Prop P_CONTROLLED;
extern const Prop P_CONTROLLER;
extern const Prop P_COMMANDED;
extern const Prop P_NAME;
extern const Prop P_PAYLOADCOUNT;
extern const Prop P_PAYLOADTYPE;
extern const Prop P_ENABLED;

extern const Thing I_COPPER;
extern const Thing I_LEAD;
extern const Thing I_COAL;
extern const Thing I_GRAPHITE;
extern const Thing I_TITANIUM;
extern const Thing I_THORIUM;
extern const Thing I_SILICON;
extern const Thing I_PLASTANIUM;
extern const Thing I_PHASE_FABRIC;
extern const Thing I_SURGE_ALLOY;
extern const Thing I_SPORE_POD;
extern const Thing I_SAND;
extern const Thing I_BLAST_COMPOUND;
extern const Thing I_PYRATITE;
extern const Thing I_METAGLASS;
extern const Thing I_SCRAP;
extern const Thing L_WATER;
extern const Thing L_SLAG;
extern const Thing L_OIL;
extern const Thing L_CRYOFLUID;
extern const Thing U_DAGGER;
extern const Thing U_MACE;
extern const Thing U_FORTRESS;
extern const Thing U_NOVA;
extern const Thing U_PULSAR;
extern const Thing U_QUASAR;
extern const Thing U_CRAWLER;
extern const Thing U_ATRAX;
extern const Thing U_SPIROCT;
extern const Thing U_ARKYID;
extern const Thing U_TOXOPID;
extern const Thing U_FLARE;
extern const Thing U_HORIZON;
extern const Thing U_ZENITH;
extern const Thing U_ANTUMBRA;
extern const Thing U_ECLIPSE;
extern const Thing U_MONO;
extern const Thing U_POLY;
extern const Thing U_MEGA;
extern const Thing U_QUAD;
extern const Thing U_OCT;
extern const Thing U_RISSO;
extern const Thing U_MINKE;
extern const Thing U_BRYDE;
extern const Thing U_SEI;
extern const Thing U_OMURA;
extern const Thing U_RETUSA;
extern const Thing U_OXYNOE;
extern const Thing U_CYERCE;
extern const Thing U_AEGIRES;
extern const Thing U_NAVANAX;
extern const Thing U_ALPHA;
extern const Thing U_BETA;
extern const Thing U_GAMMA;
extern const Thing U_SCEPTER;
extern const Thing U_REIGN;
extern const Thing U_VELA;
extern const Thing U_CORVUS;
extern const Thing B_PARALLAX;
extern const Thing B_CLIFF;
extern const Thing B_SAND_BOULDER;
extern const Thing B_BASALT_BOULDER;
extern const Thing B_GRASS;
extern const Thing B_SLAG;
extern const Thing B_SPACE;
extern const Thing B_SALT;
extern const Thing B_SALT_WALL;
extern const Thing B_PEBBLES;
extern const Thing B_TENDRILS;
extern const Thing B_SAND_WALL;
extern const Thing B_SPORE_PINE;
extern const Thing B_SPORE_WALL;
extern const Thing B_BOULDER;
extern const Thing B_SNOW_BOULDER;
extern const Thing B_SNOW_PINE;
extern const Thing B_SHALE;
extern const Thing B_SHALE_BOULDER;
extern const Thing B_MOSS;
extern const Thing B_SHRUBS;
extern const Thing B_SPORE_MOSS;
extern const Thing B_SHALE_WALL;
extern const Thing B_SCRAP_WALL;
extern const Thing B_SCRAP_WALL_LARGE;
extern const Thing B_SCRAP_WALL_HUGE;
extern const Thing B_SCRAP_WALL_GIGANTIC;
extern const Thing B_THRUSTER;
extern const Thing B_KILN;
extern const Thing B_GRAPHITE_PRESS;
extern const Thing B_MULTI_PRESS;
extern const Thing B_CONSTRUCTING;
extern const Thing B_SPAWN;
extern const Thing B_CORE_SHARD;
extern const Thing B_CORE_FOUNDATION;
extern const Thing B_CORE_NUCLEUS;
extern const Thing B_DEEPWATER;
extern const Thing B_WATER;
extern const Thing B_TAINTED_WATER;
extern const Thing B_DARKSAND_TAINTED_WATERA;
extern const Thing B_TAR;
extern const Thing B_STONE;
extern const Thing B_SAND;
extern const Thing B_DARKSAND;
extern const Thing B_ICE;
extern const Thing B_SNOW;
extern const Thing B_CRATERS;
extern const Thing B_SAND_WATER;
extern const Thing B_DARKSAND_WATER;
extern const Thing B_CHAR;
extern const Thing B_DACITE;
extern const Thing B_RHYOLITE;
extern const Thing B_DACITE_WALL;
extern const Thing B_DACITE_BOULDER;
extern const Thing B_ICE_SNOW;
extern const Thing B_STONE_WALL;
extern const Thing B_ICE_WALL;
extern const Thing B_SNOW_WALL;
extern const Thing B_DUNE_WALL;
extern const Thing B_PINE;
extern const Thing B_DIRT;
extern const Thing B_DIRT_WALL;
extern const Thing B_MUD;
extern const Thing B_WHITE_TREE_DEAD;
extern const Thing B_WHITE_TREE;
extern const Thing B_SPORE_CLUSTER;
extern const Thing B_METAL_FLOOR;
extern const Thing B_METAL_FLOOR_2;
extern const Thing B_METAL_FLOOR_3;
extern const Thing B_METAL_FLOOR_4;
extern const Thing B_METAL_FLOOR_5;
extern const Thing B_METAL_FLOOR_DAMAGED;
extern const Thing B_DARK_PANEL_1;
extern const Thing B_DARK_PANEL_2;
extern const Thing B_DARK_PANEL_3;
extern const Thing B_DARK_PANEL_4;
extern const Thing B_DARK_PANEL_5;
extern const Thing B_DARK_PANEL_6;
extern const Thing B_DARK_METAL;
extern const Thing B_BASALT;
extern const Thing B_HOTROCK;
extern const Thing B_MAGMAROCK;
extern const Thing B_COPPER_WALL;
extern const Thing B_COPPER_WALL_LARGE;
extern const Thing B_TITANIUM_WALL;
extern const Thing B_TITANIUM_WALL_LARGE;
extern const Thing B_PLASTANIUM_WALL;
extern const Thing B_PLASTANIUM_WALL_LARGE;
extern const Thing B_PHASE_WALL;
extern const Thing B_PHASE_WALL_LARGE;
extern const Thing B_THORIUM_WALL;
extern const Thing B_THORIUM_WALL_LARGE;
extern const Thing B_DOOR;
extern const Thing B_DOOR_LARGE;
extern const Thing B_DUO;
extern const Thing B_SCORCH;
extern const Thing B_SCATTER;
extern const Thing B_HAIL;
extern const Thing B_LANCER;
extern const Thing B_CONVEYOR;
extern const Thing B_TITANIUM_CONVEYOR;
extern const Thing B_PLASTANIUM_CONVEYOR;
extern const Thing B_ARMORED_CONVEYOR;
extern const Thing B_JUNCTION;
extern const Thing B_ROUTER;
extern const Thing B_DISTRIBUTOR;
extern const Thing B_SORTER;
extern const Thing B_INVERTED_SORTER;
extern const Thing B_MESSAGE;
extern const Thing B_ILLUMINATOR;
extern const Thing B_OVERFLOW_GATE;
extern const Thing B_UNDERFLOW_GATE;
extern const Thing B_SILICON_SMELTER;
extern const Thing B_PHASE_WEAVER;
extern const Thing B_PULVERIZER;
extern const Thing B_CRYOFLUID_MIXER;
extern const Thing B_MELTER;
extern const Thing B_INCINERATOR;
extern const Thing B_SPORE_PRESS;
extern const Thing B_SEPARATOR;
extern const Thing B_COAL_CENTRIFUGE;
extern const Thing B_POWER_NODE;
extern const Thing B_POWER_NODE_LARGE;
extern const Thing B_SURGE_TOWER;
extern const Thing B_DIODE;
extern const Thing B_BATTERY;
extern const Thing B_BATTERY_LARGE;
extern const Thing B_COMBUSTION_GENERATOR;
extern const Thing B_STEAM_GENERATOR;
extern const Thing B_DIFFERENTIAL_GENERATOR;
extern const Thing B_IMPACT_REACTOR;
extern const Thing B_MECHANICAL_DRILL;
extern const Thing B_PNEUMATIC_DRILL;
extern const Thing B_LASER_DRILL;
extern const Thing B_WATER_EXTRACTOR;
extern const Thing B_CULTIVATOR;
extern const Thing B_CONDUIT;
extern const Thing B_MECHANICAL_PUMP;
extern const Thing B_ITEM_SOURCE;
extern const Thing B_ITEM_VOID;
extern const Thing B_LIQUID_SOURCE;
extern const Thing B_LIQUID_VOID;
extern const Thing B_POWER_VOID;
extern const Thing B_POWER_SOURCE;
extern const Thing B_UNLOADER;
extern const Thing B_VAULT;
extern const Thing B_WAVE;
extern const Thing B_TSUNAMI;
extern const Thing B_SWARMER;
extern const Thing B_SALVO;
extern const Thing B_RIPPLE;
extern const Thing B_PHASE_CONVEYOR;
extern const Thing B_BRIDGE_CONVEYOR;
extern const Thing B_PLASTANIUM_COMPRESSOR;
extern const Thing B_PYRATITE_MIXER;
extern const Thing B_BLAST_MIXER;
extern const Thing B_SOLAR_PANEL;
extern const Thing B_SOLAR_PANEL_LARGE;
extern const Thing B_OIL_EXTRACTOR;
extern const Thing B_REPAIR_POINT;
extern const Thing B_REPAIR_TURRET;
extern const Thing B_PULSE_CONDUIT;
extern const Thing B_PLATED_CONDUIT;
extern const Thing B_PHASE_CONDUIT;
extern const Thing B_LIQUID_ROUTER;
extern const Thing B_LIQUID_TANK;
extern const Thing B_LIQUID_JUNCTION;
extern const Thing B_BRIDGE_CONDUIT;
extern const Thing B_ROTARY_PUMP;
extern const Thing B_THORIUM_REACTOR;
extern const Thing B_MASS_DRIVER;
extern const Thing B_BLAST_DRILL;
extern const Thing B_THERMAL_PUMP;
extern const Thing B_THERMAL_GENERATOR;
extern const Thing B_ALLOY_SMELTER;
extern const Thing B_MENDER;
extern const Thing B_MEND_PROJECTOR;
extern const Thing B_SURGE_WALL;
extern const Thing B_SURGE_WALL_LARGE;
extern const Thing B_CYCLONE;
extern const Thing B_FUSE;
extern const Thing B_SHOCK_MINE;
extern const Thing B_OVERDRIVE_PROJECTOR;
extern const Thing B_FORCE_PROJECTOR;
extern const Thing B_ARC;
extern const Thing B_RTG_GENERATOR;
extern const Thing B_SPECTRE;
extern const Thing B_MELTDOWN;
extern const Thing B_FORESHADOW;
extern const Thing B_CONTAINER;
extern const Thing B_LAUNCH_PAD;
extern const Thing B_SEGMENT;
extern const Thing B_COMMAND_CENTER;
extern const Thing B_GROUND_FACTORY;
extern const Thing B_AIR_FACTORY;
extern const Thing B_NAVAL_FACTORY;
extern const Thing B_ADDITIVE_RECONSTRUCTOR;
extern const Thing B_MULTIPLICATIVE_RECONSTRUCTOR;
extern const Thing B_EXPONENTIAL_RECONSTRUCTOR;
extern const Thing B_TETRATIVE_RECONSTRUCTOR;
extern const Thing B_PAYLOAD_CONVEYOR;
extern const Thing B_PAYLOAD_ROUTER;
extern const Thing B_DUCT;
extern const Thing B_DUCT_ROUTER;
extern const Thing B_DUCT_BRIDGE;
extern const Thing B_PAYLOAD_PROPULSION_TOWER;
extern const Thing B_PAYLOAD_VOID;
extern const Thing B_PAYLOAD_SOURCE;
extern const Thing B_DISASSEMBLER;
extern const Thing B_SILICON_CRUCIBLE;
extern const Thing B_OVERDRIVE_DOME;
extern const Thing B_INTERPLANETARY_ACCELERATOR;
extern const Thing B_BLOCK_FORGE;
extern const Thing B_BLOCK_LOADER;
extern const Thing B_BLOCK_UNLOADER;
extern const Thing B_SWITCH;
extern const Thing B_MICRO_PROCESSOR;
extern const Thing B_LOGIC_PROCESSOR;
extern const Thing B_HYPER_PROCESSOR;
extern const Thing B_LOGIC_DISPLAY;
extern const Thing B_LARGE_LOGIC_DISPLAY;
extern const Thing B_MEMORY_CELL;
extern const Thing B_MEMORY_BANK;
extern const Thing T_BLUE;
extern const Thing T_CRUX;
extern const Thing T_SHARDED;
extern const Thing T_DERELICT;
extern const Thing T_GREEN;
extern const Thing T_PURPLE;
